FROM public.ecr.aws/lambda/python:3.11

# Install system dependencies
RUN yum install -y \
    unzip \
    wget \
    fontconfig \
    freetype \
    libX11 \
    libXcomposite \
    libXcursor \
    libXdamage \
    libXext \
    libXi \
    libXtst \
    cups-libs \
    libXScrnSaver \
    alsa-lib \
    atk \
    gtk3 \
    xorg-x11-server-Xvfb \
    xorg-x11-xauth \
    dbus-glib \
    dbus-glib-devel \
    libnss3 \
    libXrandr \
    libxshmfence \
    libgbm \
    openssl11

# Install Chrome v124 (latest available Chrome-for-Testing with valid zip)
RUN wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chrome-linux64.zip && \
    unzip chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome && \
    ln -s /opt/chrome/chrome /usr/bin/google-chrome-stable && \
    chmod +x /usr/bin/google-chrome-stable && \
    rm -rf chrome-linux64.zip

# Install Chromedriver v124 to match
RUN wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chromedriver-linux64.zip && \
    unzip chromedriver-linux64.zip && \
    mv chromedriver-linux64/chromedriver /usr/bin/chromedriver && \
    chmod +x /usr/bin/chromedriver && \
    rm -rf chromedriver-linux64.zip


# Set ENV paths for Selenium
ENV CHROME_BIN=/usr/bin/google-chrome-stable
ENV CHROMEDRIVER_PATH=/usr/bin/chromedriver
ENV PATH=$CHROMEDRIVER_PATH:$PATH

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy your app code
COPY teamScrapper.py .

# Lambda entrypoint
CMD ["teamScrapper.handler"]
